language: java

jdk: openjdk11

# The trusty build environment allows for more memory, see https://docs.travis-ci.com/user/reference/overview/
dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx6g"
  matrix:
    - TEST=RunEquiScenarioTest
    - TEST=RunLosAngelesScenarioTest#test1
    - TEST=RunLosAngelesScenarioTest#test2
    - TEST=RunDrtLosAngelesScenarioTest#test1
    # - TEST=RunDrtLosAngelesScenarioTest#test2
    
script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
